<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MemesFinderDecisionMaker.Manager\MemesFinderDecisionMaker.Manager.csproj" />
    <ProjectReference Include="..\MemesFinderDecisionMaker.Interfaces\MemesFinderDecisionMaker.Interfaces.csproj" />
  </ItemGroup>

</Project>
